version: '3'
services:
  web_core:
    image: nakahararuu/zion_resource
    environment:
      - CADDYPATH=/etc/caddycerts
      - HOST_NAME=${HOST_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - BACKEND_BASE_URL=${BACKEND_BASE_URL}
    volumes:
      - ${MOVIES_DIR}:/srv/movie
      - ./Caddyfile:/etc/Caddyfile
      - $HOME/.caddy:/etc/caddycerts
    ports:
      - '${DEV_HTTP_PORT}:2015'
      - '${HTTPS_PORT}:443'
      - '${HTTP_PORT}:80'
    restart: always
  backend:
    image: 'node:8'
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./test_data/backend_api:/home/node/app
    expose:
      - '8000'
    command: 'npx json-server --watch --host 0.0.0.0 --port 8000 ./db.json --routes ./routes.json'
    restart: always
  auth:
    image: tarent/loginsrv
    expose:
      - '8080'
    environment:
      - LOGINSRV_BACKEND=provider=simple,${USER_NAME}=${PASSWORD}
      - LOGINSRV_JWT_EXPIRY=${JWT_EXPIRY}
      - LOGINSRV_JWT_SECRET=${JWT_SECRET}
    restart: always
  auth_dummy:
    image: 'node:8'
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./test_data/auth_api:/home/node/app
    expose:
      - '3000'
    command: bash -c "npm install && npm start"
    restart: always

